use_frameworks!
platform :osx, '10.10'

target 'Algorithms' do
  pod 'Scoper', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        #        if target.name =~ /-macOS$/
            target.build_configurations.each do |config|
                config.build_settings['DYLIB_INSTALL_NAME_BASE'] = target.product_name
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
            end
        #        end
    end
end
